language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
  - go get -t -v ./...

script:
  - go test -race -v ./...
  - ./.coverage_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
